### ISSUE TITLE
Request to break out mock

### ISSUE THREAD

**Issue by lpabon** [rexray/gocsi#99]
# Summary
Requesting to break out mock and simplify it. Maybe even create a new simpler one.

# New Feature
As part of the work in [csi-sanity](https://github.com/kubernetes-csi/csi-test/tree/master/cmd/csi-sanity) we use mock CSI driver to test our testing package. We really like it. The issue is that we sometimes need to update the csi-sanity package to the latest spec and the mock driver falls behind. 

We would like to request that the mock CSI plugin be simplified and maybe moved into its own repo. We ask this because there are a lot of features in mock which are not required in for confirming csi-sanity. We are ok with a new 'mini-mock' driver which does not take any values or do anything other than what is necessary for csi-sanity. We also request that it does not depend on any other gocsi functions.

**Comment by akutz** [comment]
Hi @lpabon,

I understand the request, and it makes sense. However, even if we were to break mock into, let's say, `csi-mock` in the REX-Ray org, it would still rely on GoCSI because:

1. We believe in GoCSI and think others should use it
2. The Mock SP exists in part to validate the GoCSI middleware

If you're intent is to have an SP that does not rely on GoCSI then I recommend starting from scratch.

**Comment by lpabon** [comment]
Understood, thanks @akutz .

**Comment by akutz** [comment]
Hi @lpabon,

By the way, Mock also serves as an example of how easy GoCSI makes bootstrapping an SP. However, please feel free to copy paste any of its code for your own purpose. The files you want are in the service package.

However, there’s also zero reason to have tooling in the CSI spec package. 

You’re not validating the spec. At best it’s validation theater.

All you’re doing is validating the Mock SP and/or the tooling. Except since they depend on one another, it still requires either to be perfect. The entire point of using protobuf and gRPC is to avoid needing to validate the protocol or API model since that is generated.
